import os
import shutil
from datetime import datetime
from pathlib import Path
import pandas as pd
import openpyxl

def populate_excel():
    """
    Reads the manually audited CSV transcripts and safely injects them into 
    Column C of the official working template.
    
    Includes mandatory safety/validation checks:
    1. Backup before modifying.
    2. Exactly 30 unique, sequential items defined.
    3. Failure on any legitimately blank transcript cell.
    """
    import yaml
    config_path = Path("config/test1_metadata.yaml")
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
        
    excel_template = Path("data/working/AutoEIT Sample Audio for Transcribing_WORKING.xlsx")
    if not excel_template.exists():
        raise FileNotFoundError(f"Working workbook not found at {excel_template}")
        
    # Backup Protocol
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = Path(f"data/working/AutoEIT Sample Audio for Transcribing_WORKING_{timestamp}.bak")
    shutil.copy2(excel_template, backup_path)
    print(f"Created safety backup at {backup_path}")
    
    # Load workbook using openpyxl directly to preserve formulas/formatting
    wb = openpyxl.load_workbook(excel_template)
    csv_dir = Path("outputs/review_csv")
    
    for file_meta in config.get("files", []):
        participant_id = file_meta["participant_id"]
        sheet_name = file_meta["sheet_name"]
        
        csv_path = csv_dir / f"{participant_id}_audit.csv"
        if not csv_path.exists():
            print(f"Skipping {participant_id}: Audit CSV not found at {csv_path}")
            continue
            
        print(f"\nEvaluating final CSV for {participant_id}...")
        df = pd.read_csv(csv_path)
        
        # We only care about rows assigned to an actual integer item_number (1-30)
        # Drop unassigned segments generated by extreme drift.
        df['item_number_str'] = df['item_number'].astype(str)
        mask = df['item_number_str'].str.match(r'^\d+$')
        df_clean = df[mask].copy()
        df_clean['item_number'] = df_clean['item_number'].astype(int)
        
        # PRE-FLIGHT VALIDATION: 30 unique rows
        if len(df_clean) != 30:
            raise ValueError(f"[{participant_id}] Pre-flight validation failed: CSV contains {len(df_clean)} indexed items instead of exactly 30.")
            
        unique_items = set(df_clean['item_number'])
        expected_items = set(range(1, 31))
        
        if unique_items != expected_items:
            raise ValueError(f"[{participant_id}] Pre-flight validation failed: Items are not exactly 1 through 30. Duplicates or missing numbers detected.")
            
        # BLANK CATCHING: No empty FINAL_AUDIT_TRANSCRIPTION
        if df_clean['FINAL_AUDIT_TRANSCRIPTION'].isnull().any() or (df_clean['FINAL_AUDIT_TRANSCRIPTION'].str.strip() == "").any():
             raise ValueError(f"[{participant_id}] Pre-flight validation failed: Blank transcriptions detected. Please explicitly mark empty learner responses as [no response].")
             
        # Extract the exact string explicitly 
        sorted_df = df_clean.sort_values(by="item_number")
        final_transcripts = sorted_df['FINAL_AUDIT_TRANSCRIPTION'].tolist()
        
        # Locate correct sheet
        if sheet_name not in wb.sheetnames:
            print(f"ERROR: Cannot find sheet '{sheet_name}' in workbook.")
            continue
            
        ws = wb[sheet_name]
        
        # The workbook format specifies Column A = Sentence #, Column B = Stimulus, Column C = Transcription.
        # However, we must programmatically find where Item 1 starts, as there could be headers.
        # We assume Sentence Column is 'A' and Transcription is 'C'.
        item_counter = 1
        written_count = 0
        
        for row in range(1, ws.max_row + 10):
            val_a = ws.cell(row=row, column=1).value
            
            # Simple check if Column A corresponds to an integer 1-30
            try:
                if val_a is not None and int(val_a) == item_counter:
                    # We are on the correct row for this item.
                    # Column C is index 3
                    ws.cell(row=row, column=3, value=final_transcripts[item_counter - 1])
                    item_counter += 1
                    written_count += 1
                    if item_counter > 30:
                        break  # Finished all 30
            except ValueError:
                continue # Skip headers like "Sentence"
                
        if written_count != 30:
            print(f"WARNING: Only wrote {written_count}/30 rows for {sheet_name}. Check workbook layout.")
        else:
            print(f"Successfully injected 30 transcripts into sheet '{sheet_name}'.")
            
    # Save the populated workbook over the working copy
    wb.save(excel_template)
    print("\n✅ Workbook successfully updated and verified. Formats preserved.")

if __name__ == "__main__":
    populate_excel()
